name: Build Docker

on:
  push:
   branches: [ update ]
  pull_request:
    branches: [ update ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker image build -t "${{ secrets.DOCKER_HUB_USERNAME }}"/mergebot:latest .
        docker push "${{ secrets.DOCKER_HUB_USERNAME }}"/mergebot:latest
